apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-tc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-tc2
  template:
    metadata:
      labels:
        app: fiap-tc2
    spec:
      containers:
      - name: fiap-tc2
        image: lucascq/fiap-tc2:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: fiap-tc2-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fiap-tc2-secrets
              key: DATABASE_URL
        - name: AWS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: fiap-tc2-config
              key: AWS_ENDPOINT
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "npx prisma migrate deploy && npx prisma db seed"]