services:
    postgres:
        image: postgres:latest
        container_name: fiap_tc1_postgres
        hostname: fiap_tc1_postgres
        environment:
            POSTGRES_USER: fiap
            POSTGRES_PASSWORD: fiap
            POSTGRES_DB: fiap_tc1_db
        ports:
            - '5432:5432'
        networks:
            - fiap_tc1_network
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d fiap_tc1_db -U fiap']
            interval: 5s
            timeout: 5s
            retries: 5

    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: fiap_tc1_server
        environment:
            - DATABASE_URL=postgresql://fiap_tc_user:senha_dificil@tc-fiap-postgres.comilucshvgd.us-east-1.rds.amazonaws.com:5432/fiap_tc_db
            - AWS_ENDPOINT=http://localstack:4566
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - 3000:3000
        networks:
            - fiap_tc1_network
        volumes:
            - .:/app
            - /app/node_modules
        command: >
            sh -c "
            npx prisma generate &&
            npx prisma migrate dev --name init &&
            npx prisma migrate deploy &&
            npx prisma db seed &&
            npm run start:dev"
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

networks:
    fiap_tc1_network:
        driver: bridge

volumes:
    postgres_data:
